/*CASO NÃO TENHA O DB CRIADO NA SUA MÁQUINA E QUEIRA FAZER ISSO PELO TERMINAL: 
*/
CREATE DATABASE coletase;
 
ALTER DATABASE coletase  CHARACTER SET utf8 COLLATE utf8_general_ci; -- Alterar o charset do BD para utf8

use coletase;*/  --Usar o BD para fazer os querys abaixo:


CREATE TABLE local(
    id_local INT UNSIGNED NOT NULL AUTO_INCREMENT,
    titulo VARCHAR(50) NOT NULL,
    latitude DOUBLE NOT NULL,
    longitude DOUBLE NOT NULL,
    descricao VARCHAR(200) NOT NULL, 
    PRIMARY KEY (id_local)
);

-- TABELA CLONE QUE UTILIZAREMOS PARA RECEBER OS DADOS INSERTIDOS PELO USUÁRIO
-- A VERIFICAÇÃO INICIAL DA VERACIDADE DOS DADOS SERIA VIA TURCO MECÂNICO, E POSTERIORMENTE, SERIA AUTOMATIZADA
CREATE TABLE userinserts(
    id_inserted INT UNSIGNED NOT NULL AUTO_INCREMENT,
    titulo VARCHAR(50) NOT NULL,
    latitude DOUBLE NOT NULL,
    longitude DOUBLE NOT NULL,
    descricao VARCHAR(200) NOT NULL, 
    PRIMARY KEY (id_inserted)
);